apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/ralphbean/example?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "main" && ( "component-03/*".pathChanged() || ".tekton/component-03-push.yaml".pathChanged() || "Containerfile".pathChanged() )
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: example-app
    appstudio.openshift.io/component: component-03
    pipelines.appstudio.openshift.io/type: build
  name: component-03-on-push
  namespace: ralphbean
spec:
  params:
    - name: git-url
      value: '{{source_url}}'
    - name: revision
      value: '{{revision}}'
    - name: output-image
      value: quay.io/experiment/ralphbean/component-03:{{revision}}
    - name: dockerfile
      value: Containerfile
    - name: path-context
      value: component-03
    - name: build-source-image
      value: "true"
    - name: hermetic
      value: "true"
    - name: prefetch-input
      value: '[{"type": "pip", "path": "component-03/."}, {"type": "generic", "path": "component-03/."}]'
  taskRunTemplate: {}
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
  pipelineRef:
    name: build-pipeline
status: {}
